modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/kncatl/Oh-My-World/issues" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/kncatl/Oh-My-World" #optional

logoFile="logo.png" #optional

#credits="" #optional

authors="kncatl"

description='''
A Minecraft mod that can generate worlds using formulas.
'''

[[mixins]]
config="ohmyworld.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
